main: org.myside.template.TemplatePlugin

name: "@plugin.name@"
version: "@plugin.version@"
description: "@plugin.description@"

author: MySide
website: https://github.com/myside-oss/template-plugin

api-version: 1.15

commands: []

permissions: []